INSERT INTO suat_chieu (id, id_khung_gio, id_phong_chieu, id_phim, ngay_chieu, so_ghe_trong, trang_thai, nguoi_tao)
VALUES ('sc-1', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-2', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-3', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-4', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-5', '', 'pc-6', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-6', '', 'pc-7', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-7', '', 'pc-1', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-8', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-9', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-10', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-11', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-12', '', 'pc-6', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-13', '', 'pc-7', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-14', '', 'pc-1', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-15', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-16', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-17', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-18', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-19', '', 'pc-6', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-20', '', 'pc-7', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-21', '', 'pc-1', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-22', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-23', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-24', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-25', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-26', '', 'pc-6', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-27', '', 'pc-7', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-28', '', 'pc-1', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-29', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-30', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-31', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-32', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-33', '', 'pc-6', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-34', '', 'pc-7', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-35', '', 'pc-1', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-36', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-37', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-38', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-39', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-40', '', 'pc-6', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-41', '', 'pc-7', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-42', '', 'pc-1', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-43', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-44', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-45', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-46', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-47', '', 'pc-6', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-48', '', 'pc-7', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-49', '', 'pc-1', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-50', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-51', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-52', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-53', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-54', '', 'pc-6', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-55', '', 'pc-7', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-56', '', 'pc-1', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-57', '', 'pc-2', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-58', '', 'pc-3', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-59', '', 'pc-4', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system'),
       ('sc-60', '', 'pc-5', '', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 40, 1, 'system');

INSERT INTO ghe (id, id_loai_ghe, id_phong_chieu, so_ghe, so_hang, so_cot, trang_thai, nguoi_tao)
VALUES ('g-pc-1-A1', 'lg-1', 'pc-1', 'A1', 'A', 1, 1, 'system'),
       ('g-pc-1-A2', 'lg-1', 'pc-1', 'A2', 'A', 2, 1, 'system'),
       ('g-pc-1-A3', 'lg-1', 'pc-1', 'A3', 'A', 3, 1, 'system'),
       ('g-pc-1-A4', 'lg-1', 'pc-1', 'A4', 'A', 4, 1, 'system'),
       ('g-pc-1-A5', 'lg-1', 'pc-1', 'A5', 'A', 5, 1, 'system'),
       ('g-pc-1-A6', 'lg-1', 'pc-1', 'A6', 'A', 6, 1, 'system'),
       ('g-pc-1-A7', 'lg-1', 'pc-1', 'A7', 'A', 7, 1, 'system'),
       ('g-pc-1-A8', 'lg-1', 'pc-1', 'A8', 'A', 8, 1, 'system'),
       ('g-pc-1-B1', 'lg-1', 'pc-1', 'B1', 'B', 1, 1, 'system'),
       ('g-pc-1-B2', 'lg-1', 'pc-1', 'B2', 'B', 2, 1, 'system'),
       ('g-pc-1-B3', 'lg-1', 'pc-1', 'B3', 'B', 3, 1, 'system'),
       ('g-pc-1-B4', 'lg-1', 'pc-1', 'B4', 'B', 4, 1, 'system'),
       ('g-pc-1-B5', 'lg-1', 'pc-1', 'B5', 'B', 5, 1, 'system'),
       ('g-pc-1-B6', 'lg-1', 'pc-1', 'B6', 'B', 6, 1, 'system'),
       ('g-pc-1-B7', 'lg-1', 'pc-1', 'B7', 'B', 7, 1, 'system'),
       ('g-pc-1-B8', 'lg-1', 'pc-1', 'B8', 'B', 8, 1, 'system'),
       ('g-pc-1-C1', 'lg-1', 'pc-1', 'C1', 'C', 1, 1, 'system'),
       ('g-pc-1-C2', 'lg-1', 'pc-1', 'C2', 'C', 2, 1, 'system'),
       ('g-pc-1-C3', 'lg-1', 'pc-1', 'C3', 'C', 3, 1, 'system'),
       ('g-pc-1-C4', 'lg-1', 'pc-1', 'C4', 'C', 4, 1, 'system'),
       ('g-pc-1-C5', 'lg-1', 'pc-1', 'C5', 'C', 5, 1, 'system'),
       ('g-pc-1-C6', 'lg-1', 'pc-1', 'C6', 'C', 6, 1, 'system'),
       ('g-pc-1-C7', 'lg-1', 'pc-1', 'C7', 'C', 7, 1, 'system'),
       ('g-pc-1-C8', 'lg-1', 'pc-1', 'C8', 'C', 8, 1, 'system'),
       ('g-pc-1-D1', 'lg-2', 'pc-1', 'D1', 'D', 1, 1, 'system'),
       ('g-pc-1-D2', 'lg-2', 'pc-1', 'D2', 'D', 2, 1, 'system'),
       ('g-pc-1-D3', 'lg-2', 'pc-1', 'D3', 'D', 3, 1, 'system'),
       ('g-pc-1-D4', 'lg-2', 'pc-1', 'D4', 'D', 4, 1, 'system'),
       ('g-pc-1-D5', 'lg-2', 'pc-1', 'D5', 'D', 5, 1, 'system'),
       ('g-pc-1-D6', 'lg-2', 'pc-1', 'D6', 'D', 6, 1, 'system'),
       ('g-pc-1-D7', 'lg-2', 'pc-1', 'D7', 'D', 7, 1, 'system'),
       ('g-pc-1-D8', 'lg-2', 'pc-1', 'D8', 'D', 8, 1, 'system'),
       ('g-pc-1-E1', 'lg-3', 'pc-1', 'E1', 'E', 1, 1, 'system'),
       ('g-pc-1-E2', 'lg-3', 'pc-1', 'E2', 'E', 2, 1, 'system'),
       ('g-pc-1-E3', 'lg-2', 'pc-1', 'E3', 'E', 3, 1, 'system'),
       ('g-pc-1-E4', 'lg-2', 'pc-1', 'E4', 'E', 4, 1, 'system'),
       ('g-pc-1-E5', 'lg-2', 'pc-1', 'E5', 'E', 5, 1, 'system'),
       ('g-pc-1-E6', 'lg-2', 'pc-1', 'E6', 'E', 6, 1, 'system'),
       ('g-pc-1-E7', 'lg-2', 'pc-1', 'E7', 'E', 7, 1, 'system'),
       ('g-pc-1-E8', 'lg-2', 'pc-1', 'E8', 'E', 8, 1, 'system'),
       ('g-pc-2-A1', 'lg-2', 'pc-2', 'A1', 'A', 1, 1, 'system'),
       ('g-pc-2-A2', 'lg-2', 'pc-2', 'A2', 'A', 2, 1, 'system'),
       ('g-pc-2-A3', 'lg-2', 'pc-2', 'A3', 'A', 3, 1, 'system'),
       ('g-pc-2-A4', 'lg-2', 'pc-2', 'A4', 'A', 4, 1, 'system'),
       ('g-pc-2-A5', 'lg-2', 'pc-2', 'A5', 'A', 5, 1, 'system'),
       ('g-pc-2-B1', 'lg-2', 'pc-2', 'B1', 'B', 1, 1, 'system'),
       ('g-pc-2-B2', 'lg-2', 'pc-2', 'B2', 'B', 2, 1, 'system'),
       ('g-pc-2-B3', 'lg-2', 'pc-2', 'B3', 'B', 3, 1, 'system'),
       ('g-pc-2-B4', 'lg-2', 'pc-2', 'B4', 'B', 4, 1, 'system'),
       ('g-pc-2-B5', 'lg-2', 'pc-2', 'B5', 'B', 5, 1, 'system'),
       ('g-pc-2-C1', 'lg-2', 'pc-2', 'C1', 'C', 1, 1, 'system'),
       ('g-pc-2-C2', 'lg-2', 'pc-2', 'C2', 'C', 2, 1, 'system'),
       ('g-pc-2-C3', 'lg-2', 'pc-2', 'C3', 'C', 3, 1, 'system'),
       ('g-pc-2-C4', 'lg-2', 'pc-2', 'C4', 'C', 4, 1, 'system'),
       ('g-pc-2-C5', 'lg-2', 'pc-2', 'C5', 'C', 5, 1, 'system'),
       ('g-pc-2-D1', 'lg-2', 'pc-2', 'D1', 'D', 1, 1, 'system'),
       ('g-pc-2-D2', 'lg-2', 'pc-2', 'D2', 'D', 2, 1, 'system'),
       ('g-pc-2-D3', 'lg-2', 'pc-2', 'D3', 'D', 3, 1, 'system'),
       ('g-pc-2-D4', 'lg-2', 'pc-2', 'D4', 'D', 4, 1, 'system'),
       ('g-pc-2-D5', 'lg-2', 'pc-2', 'D5', 'D', 5, 1, 'system'),
       ('g-pc-2-E1', 'lg-2', 'pc-2', 'E1', 'E', 1, 1, 'system'),
       ('g-pc-2-E2', 'lg-2', 'pc-2', 'E2', 'E', 2, 1, 'system'),
       ('g-pc-2-E3', 'lg-2', 'pc-2', 'E3', 'E', 3, 1, 'system'),
       ('g-pc-2-E4', 'lg-2', 'pc-2', 'E4', 'E', 4, 1, 'system'),
       ('g-pc-2-E5', 'lg-2', 'pc-2', 'E5', 'E', 5, 1, 'system'),
       ('g-pc-2-F1', 'lg-3', 'pc-2', 'F1', 'F', 1, 1, 'system'),
       ('g-pc-2-F2', 'lg-3', 'pc-2', 'F2', 'F', 2, 1, 'system'),
       ('g-pc-2-F3', 'lg-2', 'pc-2', 'F3', 'F', 3, 1, 'system'),
       ('g-pc-2-F4', 'lg-2', 'pc-2', 'F4', 'F', 4, 1, 'system'),
       ('g-pc-2-F5', 'lg-2', 'pc-2', 'F5', 'F', 5, 1, 'system'),
       ('g-pc-3-A1', 'lg-1', 'pc-3', 'A1', 'A', 1, 1, 'system'),
       ('g-pc-3-A2', 'lg-1', 'pc-3', 'A2', 'A', 2, 1, 'system'),
       ('g-pc-3-A3', 'lg-1', 'pc-3', 'A3', 'A', 3, 1, 'system'),
       ('g-pc-3-A4', 'lg-1', 'pc-3', 'A4', 'A', 4, 1, 'system'),
       ('g-pc-3-A5', 'lg-1', 'pc-3', 'A5', 'A', 5, 1, 'system'),
       ('g-pc-3-A6', 'lg-1', 'pc-3', 'A6', 'A', 6, 1, 'system'),
       ('g-pc-3-A7', 'lg-1', 'pc-3', 'A7', 'A', 7, 1, 'system'),
       ('g-pc-3-A8', 'lg-1', 'pc-3', 'A8', 'A', 8, 1, 'system'),
       ('g-pc-3-B1', 'lg-1', 'pc-3', 'B1', 'B', 1, 1, 'system'),
       ('g-pc-3-B2', 'lg-1', 'pc-3', 'B2', 'B', 2, 1, 'system'),
       ('g-pc-3-B3', 'lg-1', 'pc-3', 'B3', 'B', 3, 1, 'system'),
       ('g-pc-3-B4', 'lg-1', 'pc-3', 'B4', 'B', 4, 1, 'system'),
       ('g-pc-3-B5', 'lg-1', 'pc-3', 'B5', 'B', 5, 1, 'system'),
       ('g-pc-3-B6', 'lg-1', 'pc-3', 'B6', 'B', 6, 1, 'system'),
       ('g-pc-3-B7', 'lg-1', 'pc-3', 'B7', 'B', 7, 1, 'system'),
       ('g-pc-3-B8', 'lg-1', 'pc-3', 'B8', 'B', 8, 1, 'system'),
       ('g-pc-3-C1', 'lg-1', 'pc-3', 'C1', 'C', 1, 1, 'system'),
       ('g-pc-3-C2', 'lg-1', 'pc-3', 'C2', 'C', 2, 1, 'system'),
       ('g-pc-3-C3', 'lg-1', 'pc-3', 'C3', 'C', 3, 1, 'system'),
       ('g-pc-3-C4', 'lg-1', 'pc-3', 'C4', 'C', 4, 1, 'system'),
       ('g-pc-3-C5', 'lg-1', 'pc-3', 'C5', 'C', 5, 1, 'system'),
       ('g-pc-3-C6', 'lg-1', 'pc-3', 'C6', 'C', 6, 1, 'system'),
       ('g-pc-3-C7', 'lg-1', 'pc-3', 'C7', 'C', 7, 1, 'system'),
       ('g-pc-3-C8', 'lg-1', 'pc-3', 'C8', 'C', 8, 1, 'system'),
       ('g-pc-3-D1', 'lg-2', 'pc-3', 'D1', 'D', 1, 1, 'system'),
       ('g-pc-3-D2', 'lg-2', 'pc-3', 'D2', 'D', 2, 1, 'system'),
       ('g-pc-3-D3', 'lg-2', 'pc-3', 'D3', 'D', 3, 1, 'system'),
       ('g-pc-3-D4', 'lg-2', 'pc-3', 'D4', 'D', 4, 1, 'system'),
       ('g-pc-3-D5', 'lg-2', 'pc-3', 'D5', 'D', 5, 1, 'system'),
       ('g-pc-3-D6', 'lg-2', 'pc-3', 'D6', 'D', 6, 1, 'system'),
       ('g-pc-3-D7', 'lg-2', 'pc-3', 'D7', 'D', 7, 1, 'system'),
       ('g-pc-3-D8', 'lg-2', 'pc-3', 'D8', 'D', 8, 1, 'system'),
       ('g-pc-3-E1', 'lg-3', 'pc-3', 'E1', 'E', 1, 1, 'system'),
       ('g-pc-3-E2', 'lg-3', 'pc-3', 'E2', 'E', 2, 1, 'system'),
       ('g-pc-3-E3', 'lg-2', 'pc-3', 'E3', 'E', 3, 1, 'system'),
       ('g-pc-3-E4', 'lg-2', 'pc-3', 'E4', 'E', 4, 1, 'system'),
       ('g-pc-3-E5', 'lg-2', 'pc-3', 'E5', 'E', 5, 1, 'system'),
       ('g-pc-3-E6', 'lg-2', 'pc-3', 'E6', 'E', 6, 1, 'system'),
       ('g-pc-3-E7', 'lg-2', 'pc-3', 'E7', 'E', 7, 1, 'system'),
       ('g-pc-3-E8', 'lg-2', 'pc-3', 'E8', 'E', 8, 1, 'system'),
       ('g-pc-4-A1', 'lg-1', 'pc-4', 'A1', 'A', 1, 1, 'system'),
       ('g-pc-4-A2', 'lg-1', 'pc-4', 'A2', 'A', 2, 1, 'system'),
       ('g-pc-4-A3', 'lg-1', 'pc-4', 'A3', 'A', 3, 1, 'system'),
       ('g-pc-4-A4', 'lg-1', 'pc-4', 'A4', 'A', 4, 1, 'system'),
       ('g-pc-4-A5', 'lg-1', 'pc-4', 'A5', 'A', 5, 1, 'system'),
       ('g-pc-4-A6', 'lg-1', 'pc-4', 'A6', 'A', 6, 1, 'system'),
       ('g-pc-4-B1', 'lg-1', 'pc-4', 'B1', 'B', 1, 1, 'system'),
       ('g-pc-4-B2', 'lg-1', 'pc-4', 'B2', 'B', 2, 1, 'system'),
       ('g-pc-4-B3', 'lg-1', 'pc-4', 'B3', 'B', 3, 1, 'system'),
       ('g-pc-4-B4', 'lg-1', 'pc-4', 'B4', 'B', 4, 1, 'system'),
       ('g-pc-4-B5', 'lg-1', 'pc-4', 'B5', 'B', 5, 1, 'system'),
       ('g-pc-4-B6', 'lg-1', 'pc-4', 'B6', 'B', 6, 1, 'system'),
       ('g-pc-4-C1', 'lg-1', 'pc-4', 'C1', 'C', 1, 1, 'system'),
       ('g-pc-4-C2', 'lg-1', 'pc-4', 'C2', 'C', 2, 1, 'system'),
       ('g-pc-4-C3', 'lg-1', 'pc-4', 'C3', 'C', 3, 1, 'system'),
       ('g-pc-4-C4', 'lg-1', 'pc-4', 'C4', 'C', 4, 1, 'system'),
       ('g-pc-4-C5', 'lg-1', 'pc-4', 'C5', 'C', 5, 1, 'system'),
       ('g-pc-4-C6', 'lg-1', 'pc-4', 'C6', 'C', 6, 1, 'system'),
       ('g-pc-4-D1', 'lg-2', 'pc-4', 'D1', 'D', 1, 1, 'system'),
       ('g-pc-4-D2', 'lg-2', 'pc-4', 'D2', 'D', 2, 1, 'system'),
       ('g-pc-4-D3', 'lg-2', 'pc-4', 'D3', 'D', 3, 1, 'system'),
       ('g-pc-4-D4', 'lg-2', 'pc-4', 'D4', 'D', 4, 1, 'system'),
       ('g-pc-4-D5', 'lg-2', 'pc-4', 'D5', 'D', 5, 1, 'system'),
       ('g-pc-4-D6', 'lg-2', 'pc-4', 'D6', 'D', 6, 1, 'system'),
       ('g-pc-4-E1', 'lg-3', 'pc-4', 'E1', 'E', 1, 1, 'system'),
       ('g-pc-4-E2', 'lg-3', 'pc-4', 'E2', 'E', 2, 1, 'system'),
       ('g-pc-4-E3', 'lg-2', 'pc-4', 'E3', 'E', 3, 1, 'system'),
       ('g-pc-4-E4', 'lg-2', 'pc-4', 'E4', 'E', 4, 1, 'system'),
       ('g-pc-4-E5', 'lg-2', 'pc-4', 'E5', 'E', 5, 1, 'system'),
       ('g-pc-4-E6', 'lg-2', 'pc-4', 'E6', 'E', 6, 1, 'system'),
       ('g-pc-5-A1', 'lg-2', 'pc-5', 'A1', 'A', 1, 1, 'system'),
       ('g-pc-5-A2', 'lg-2', 'pc-5', 'A2', 'A', 2, 1, 'system'),
       ('g-pc-5-A3', 'lg-2', 'pc-5', 'A3', 'A', 3, 1, 'system'),
       ('g-pc-5-A4', 'lg-2', 'pc-5', 'A4', 'A', 4, 1, 'system'),
       ('g-pc-5-A5', 'lg-2', 'pc-5', 'A5', 'A', 5, 1, 'system'),
       ('g-pc-5-B1', 'lg-2', 'pc-5', 'B1', 'B', 1, 1, 'system'),
       ('g-pc-5-B2', 'lg-2', 'pc-5', 'B2', 'B', 2, 1, 'system'),
       ('g-pc-5-B3', 'lg-2', 'pc-5', 'B3', 'B', 3, 1, 'system'),
       ('g-pc-5-B4', 'lg-2', 'pc-5', 'B4', 'B', 4, 1, 'system'),
       ('g-pc-5-B5', 'lg-2', 'pc-5', 'B5', 'B', 5, 1, 'system'),
       ('g-pc-5-C1', 'lg-2', 'pc-5', 'C1', 'C', 1, 1, 'system'),
       ('g-pc-5-C2', 'lg-2', 'pc-5', 'C2', 'C', 2, 1, 'system'),
       ('g-pc-5-C3', 'lg-2', 'pc-5', 'C3', 'C', 3, 1, 'system'),
       ('g-pc-5-C4', 'lg-2', 'pc-5', 'C4', 'C', 4, 1, 'system'),
       ('g-pc-5-C5', 'lg-2', 'pc-5', 'C5', 'C', 5, 1, 'system'),
       ('g-pc-5-D1', 'lg-2', 'pc-5', 'D1', 'D', 1, 1, 'system'),
       ('g-pc-5-D2', 'lg-2', 'pc-5', 'D2', 'D', 2, 1, 'system'),
       ('g-pc-5-D3', 'lg-2', 'pc-5', 'D3', 'D', 3, 1, 'system'),
       ('g-pc-5-D4', 'lg-2', 'pc-5', 'D4', 'D', 4, 1, 'system'),
       ('g-pc-5-D5', 'lg-2', 'pc-5', 'D5', 'D', 5, 1, 'system'),
       ('g-pc-5-E1', 'lg-2', 'pc-5', 'E1', 'E', 1, 1, 'system'),
       ('g-pc-5-E2', 'lg-2', 'pc-5', 'E2', 'E', 2, 1, 'system'),
       ('g-pc-5-E3', 'lg-2', 'pc-5', 'E3', 'E', 3, 1, 'system'),
       ('g-pc-5-E4', 'lg-2', 'pc-5', 'E4', 'E', 4, 1, 'system'),
       ('g-pc-5-E5', 'lg-2', 'pc-5', 'E5', 'E', 5, 1, 'system'),
       ('g-pc-5-F1', 'lg-3', 'pc-5', 'F1', 'F', 1, 1, 'system'),
       ('g-pc-5-F2', 'lg-3', 'pc-5', 'F2', 'F', 2, 1, 'system'),
       ('g-pc-5-F3', 'lg-2', 'pc-5', 'F3', 'F', 3, 1, 'system'),
       ('g-pc-5-F4', 'lg-2', 'pc-5', 'F4', 'F', 4, 1, 'system'),
       ('g-pc-5-F5', 'lg-2', 'pc-5', 'F5', 'F', 5, 1, 'system'),
       ('g-pc-6-A1', 'lg-1', 'pc-6', 'A1', 'A', 1, 1, 'system'),
       ('g-pc-6-A2', 'lg-1', 'pc-6', 'A2', 'A', 2, 1, 'system'),
       ('g-pc-6-A3', 'lg-1', 'pc-6', 'A3', 'A', 3, 1, 'system'),
       ('g-pc-6-A4', 'lg-1', 'pc-6', 'A4', 'A', 4, 1, 'system'),
       ('g-pc-6-A5', 'lg-1', 'pc-6', 'A5', 'A', 5, 1, 'system'),
       ('g-pc-6-A6', 'lg-1', 'pc-6', 'A6', 'A', 6, 1, 'system'),
       ('g-pc-6-A7', 'lg-1', 'pc-6', 'A7', 'A', 7, 1, 'system'),
       ('g-pc-6-A8', 'lg-1', 'pc-6', 'A8', 'A', 8, 1, 'system'),
       ('g-pc-6-B1', 'lg-1', 'pc-6', 'B1', 'B', 1, 1, 'system'),
       ('g-pc-6-B2', 'lg-1', 'pc-6', 'B2', 'B', 2, 1, 'system'),
       ('g-pc-6-B3', 'lg-1', 'pc-6', 'B3', 'B', 3, 1, 'system'),
       ('g-pc-6-B4', 'lg-1', 'pc-6', 'B4', 'B', 4, 1, 'system'),
       ('g-pc-6-B5', 'lg-1', 'pc-6', 'B5', 'B', 5, 1, 'system'),
       ('g-pc-6-B6', 'lg-1', 'pc-6', 'B6', 'B', 6, 1, 'system'),
       ('g-pc-6-B7', 'lg-1', 'pc-6', 'B7', 'B', 7, 1, 'system'),
       ('g-pc-6-B8', 'lg-1', 'pc-6', 'B8', 'B', 8, 1, 'system'),
       ('g-pc-6-C1', 'lg-1', 'pc-6', 'C1', 'C', 1, 1, 'system'),
       ('g-pc-6-C2', 'lg-1', 'pc-6', 'C2', 'C', 2, 1, 'system'),
       ('g-pc-6-C3', 'lg-1', 'pc-6', 'C3', 'C', 3, 1, 'system'),
       ('g-pc-6-C4', 'lg-1', 'pc-6', 'C4', 'C', 4, 1, 'system'),
       ('g-pc-6-C5', 'lg-1', 'pc-6', 'C5', 'C', 5, 1, 'system'),
       ('g-pc-6-C6', 'lg-1', 'pc-6', 'C6', 'C', 6, 1, 'system'),
       ('g-pc-6-C7', 'lg-1', 'pc-6', 'C7', 'C', 7, 1, 'system'),
       ('g-pc-6-C8', 'lg-1', 'pc-6', 'C8', 'C', 8, 1, 'system'),
       ('g-pc-6-D1', 'lg-2', 'pc-6', 'D1', 'D', 1, 1, 'system'),
       ('g-pc-6-D2', 'lg-2', 'pc-6', 'D2', 'D', 2, 1, 'system'),
       ('g-pc-6-D3', 'lg-2', 'pc-6', 'D3', 'D', 3, 1, 'system'),
       ('g-pc-6-D4', 'lg-2', 'pc-6', 'D4', 'D', 4, 1, 'system'),
       ('g-pc-6-D5', 'lg-2', 'pc-6', 'D5', 'D', 5, 1, 'system'),
       ('g-pc-6-D6', 'lg-2', 'pc-6', 'D6', 'D', 6, 1, 'system'),
       ('g-pc-6-D7', 'lg-2', 'pc-6', 'D7', 'D', 7, 1, 'system'),
       ('g-pc-6-D8', 'lg-2', 'pc-6', 'D8', 'D', 8, 1, 'system'),
       ('g-pc-6-E1', 'lg-3', 'pc-6', 'E1', 'E', 1, 1, 'system'),
       ('g-pc-6-E2', 'lg-3', 'pc-6', 'E2', 'E', 2, 1, 'system'),
       ('g-pc-6-E3', 'lg-2', 'pc-6', 'E3', 'E', 3, 1, 'system'),
       ('g-pc-6-E4', 'lg-2', 'pc-6', 'E4', 'E', 4, 1, 'system'),
       ('g-pc-6-E5', 'lg-2', 'pc-6', 'E5', 'E', 5, 1, 'system'),
       ('g-pc-6-E6', 'lg-2', 'pc-6', 'E6', 'E', 6, 1, 'system'),
       ('g-pc-6-E7', 'lg-2', 'pc-6', 'E7', 'E', 7, 1, 'system'),
       ('g-pc-6-E8', 'lg-2', 'pc-6', 'E8', 'E', 8, 1, 'system'),
       ('g-pc-7-A1', 'lg-1', 'pc-7', 'A1', 'A', 1, 1, 'system'),
       ('g-pc-7-A2', 'lg-1', 'pc-7', 'A2', 'A', 2, 1, 'system'),
       ('g-pc-7-A3', 'lg-1', 'pc-7', 'A3', 'A', 3, 1, 'system'),
       ('g-pc-7-A4', 'lg-1', 'pc-7', 'A4', 'A', 4, 1, 'system'),
       ('g-pc-7-A5', 'lg-1', 'pc-7', 'A5', 'A', 5, 1, 'system'),
       ('g-pc-7-A6', 'lg-1', 'pc-7', 'A6', 'A', 6, 1, 'system'),
       ('g-pc-7-A7', 'lg-1', 'pc-7', 'A7', 'A', 7, 1, 'system'),
       ('g-pc-7-A8', 'lg-1', 'pc-7', 'A8', 'A', 8, 1, 'system'),
       ('g-pc-7-A9', 'lg-1', 'pc-7', 'A9', 'A', 9, 1, 'system'),
       ('g-pc-7-A10', 'lg-1', 'pc-7', 'A10', 'A', 10, 1, 'system'),
       ('g-pc-7-B1', 'lg-1', 'pc-7', 'B1', 'B', 1, 1, 'system'),
       ('g-pc-7-B2', 'lg-1', 'pc-7', 'B2', 'B', 2, 1, 'system'),
       ('g-pc-7-B3', 'lg-1', 'pc-7', 'B3', 'B', 3, 1, 'system'),
       ('g-pc-7-B4', 'lg-1', 'pc-7', 'B4', 'B', 4, 1, 'system'),
       ('g-pc-7-B5', 'lg-1', 'pc-7', 'B5', 'B', 5, 1, 'system'),
       ('g-pc-7-B6', 'lg-1', 'pc-7', 'B6', 'B', 6, 1, 'system'),
       ('g-pc-7-B7', 'lg-1', 'pc-7', 'B7', 'B', 7, 1, 'system'),
       ('g-pc-7-B8', 'lg-1', 'pc-7', 'B8', 'B', 8, 1, 'system'),
       ('g-pc-7-B9', 'lg-1', 'pc-7', 'B9', 'B', 9, 1, 'system'),
       ('g-pc-7-B10', 'lg-1', 'pc-7', 'B10', 'B', 10, 1, 'system'),
       ('g-pc-7-C1', 'lg-1', 'pc-7', 'C1', 'C', 1, 1, 'system'),
       ('g-pc-7-C2', 'lg-1', 'pc-7', 'C2', 'C', 2, 1, 'system'),
       ('g-pc-7-C3', 'lg-1', 'pc-7', 'C3', 'C', 3, 1, 'system'),
       ('g-pc-7-C4', 'lg-1', 'pc-7', 'C4', 'C', 4, 1, 'system'),
       ('g-pc-7-C5', 'lg-1', 'pc-7', 'C5', 'C', 5, 1, 'system'),
       ('g-pc-7-C6', 'lg-1', 'pc-7', 'C6', 'C', 6, 1, 'system'),
       ('g-pc-7-C7', 'lg-1', 'pc-7', 'C7', 'C', 7, 1, 'system'),
       ('g-pc-7-C8', 'lg-1', 'pc-7', 'C8', 'C', 8, 1, 'system'),
       ('g-pc-7-C9', 'lg-1', 'pc-7', 'C9', 'C', 9, 1, 'system'),
       ('g-pc-7-C10', 'lg-1', 'pc-7', 'C10', 'C', 10, 1, 'system'),
       ('g-pc-7-D1', 'lg-3', 'pc-7', 'D1', 'D', 1, 1, 'system'),
       ('g-pc-7-D2', 'lg-3', 'pc-7', 'D2', 'D', 2, 1, 'system'),
       ('g-pc-7-D3', 'lg-2', 'pc-7', 'D3', 'D', 3, 1, 'system'),
       ('g-pc-7-D4', 'lg-2', 'pc-7', 'D4', 'D', 4, 1, 'system'),
       ('g-pc-7-D5', 'lg-2', 'pc-7', 'D5', 'D', 5, 1, 'system'),
       ('g-pc-7-D6', 'lg-2', 'pc-7', 'D6', 'D', 6, 1, 'system'),
       ('g-pc-7-D7', 'lg-2', 'pc-7', 'D7', 'D', 7, 1, 'system'),
       ('g-pc-7-D8', 'lg-2', 'pc-7', 'D8', 'D', 8, 1, 'system'),
       ('g-pc-7-D9', 'lg-2', 'pc-7', 'D9', 'D', 9, 1, 'system'),
       ('g-pc-7-D10', 'lg-2', 'pc-7', 'D10', 'D', 10, 1, 'system');
